from typing import Dict
from uuid import UUID
import os, redis.asyncio as redis, logging
from asyncio import TimeoutError, sleep
from redis.exceptions import ResponseError, TimeoutError
from src.utils.logging_config import configure_logging
from src.utils.constants import redis_labels
from src.schemas.response_models import SinglePrediction

# persistent Redis Client store
_RedisClientCache = {}

def get_redis(client_task_name:str):
    """
    Check if a redis client is cached or not.
    Return it if yes, else create and cache a new client and then return it
    """
    if client_task_name not in _RedisClientCache:
        redis_host = "redis_container" if os.environ.get("IS_DOCKER")=="1" else "localhost"
        _RedisClientCache[client_task_name] = redis.Redis(host=redis_host, 
                                                          port=6379, db=0,
                                                          # socker_timeout should be decently greater than the block time 
                                                          # in the worker's Xread/Xgroupreads or there's the chance of 
                                                          # redis stream connection drop
                                                          socket_timeout=15, 
                                                          socket_keepalive=True)
        # print(redis_client.connection_pool.connection_kwargs) # debug print statement to check connection args
    return _RedisClientCache[client_task_name]

# configure logging and labels
configure_logging()
logger = logging.getLogger(__name__)
GROUP_NAME = redis_labels.GROUP_NAME.value
JOB_STREAM_NAME = redis_labels.JOB_STREAM_NAME.value
RESULT_STREAM_NAME = redis_labels.RESULT_STREAM_NAME.value

# working functions for redis implementation
async def create_worker_group(redis_client):
    try:
        await redis_client.xgroup_create(JOB_STREAM_NAME, GROUP_NAME, id="$", mkstream=True)
    except ResponseError as e:
        if "BUSYGROUP" in str(e):
            pass  # group already exists
        else:
            raise

async def add_image_job(redis_client,image_filename:str,image_bytes:bytes, job_id:UUID, batch_id:UUID):
    """
    Helper function that creates and posts an image job to a Redis Stream.
    Input Params: redis_client - The redis client the app/program uses to connect to a Redis instance
                : image_filename - A string value for the image's filename
                : image_bytes - The actual image data in bytes
                : job_id - A unique ID generated by the app/program for each job
                : batch_id - A unique ID generated for each batch of jobs (denoting the same zip source)
    """
    return await redis_client.xadd(name=JOB_STREAM_NAME,fields={
        "job_id":job_id,
        "batch_id":batch_id,
        "image_filename":image_filename,
        "image_data":image_bytes.hex(),
        "task":"classify"
    })

async def add_image_result(redis_client,result:SinglePrediction, job_id:UUID, batch_id:UUID):
    """
    Helper function that posts the result of an image job to a batch_id scoped result stream for dispatcher to gather.
    Input Params: redis_client - The redis client the app/program uses to connect to a Redis instance
                : result - A SInglePrediction object containing the results for one image job'
                : job_id - A unique ID generated by the app/program for each job
                : batch_id - A unique ID generated for each batch of jobs (denoting the same zip source)
    """
    return await redis_client.xadd(name=f"{RESULT_STREAM_NAME}-{batch_id}",fields={
        "job_id":job_id,
        "filename":result.filename,
        "predicted_class":result.predicted_class,
        "confidence":result.confidence
    })

async def worker(redis_client,predict_fn, worker_id):
    """
    The inference worker function. This is what runs inference per instance, self-polling job stream for new jobs and posting results to result stream.
    Input Params: redis_client - The redis client the app/program uses to connect to a Redis instance
                : predict_fn - The function to use to run inference
                : worker_id - A unique ID generated by the app/program for each worker, appended after 'worker'
    """
    consumer_name = f"worker-{worker_id}"
    logger.info(f"Worker {worker_id} started!")

    while True:
        try:
            resp = await redis_client.xreadgroup(
                groupname=GROUP_NAME,
                consumername=consumer_name,
                streams={JOB_STREAM_NAME: ">"},  # ">" = only new messages
                count=1,
                block=5000
            )

            if not resp:
                continue

            for _, messages in resp:
                if not isinstance(messages, list):
                    continue
                for message_id, fields in messages:
                    await predict_fn(redis_client=redis_client,fields=fields)
                    logger.info(f"Worker {worker_id} Processed an Image!")
        except(TimeoutError, TimeoutError) as e:
            logger.warning("Timeout occurred, retrying...", e)
            await sleep(1)
            continue
