FROM python:3.12.5-slim as builder

WORKDIR /build

# Copy requirements from root
COPY requirements.txt .
RUN pip install --user --no-cache-dir -r requirements.txt

# Run Image
FROM python:3.12.5-slim

WORKDIR /img-classifier
COPY --from=builder /root/.local /root/.local

# Copy src code, includes scripts and saved model
COPY src/ ./src

ENV PATH=/root/.local/bin:$PATH
ENV PYTHONPATH=/img-classifier
EXPOSE 8000
ENTRYPOINT ["python","-m", "src.run"]
CMD ["--server"]